### ISSUE TITLE
Cannot use the package with latest Laravel 11

### ISSUE THREAD

**Issue by troccoli** [NoelDeMartin/cypress-laravel#12]
I have a new Laravel 11 app and installing the package returns a lot of issues, with a few packages being deprecated and high and critical vulnerabilities
```
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm warn deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm warn deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142

added 174 packages, and audited 562 packages in 4s

120 packages are looking for funding
  run `npm fund` for details

12 vulnerabilities (2 low, 2 moderate, 4 high, 4 critical)

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
```

I have tried to submit a PR with new updated versions of the packages (#11), but although that resoled the deprecations and the vulnerabilities, it also broke the package (this package) `npm run build`.

I'm quite unfamiliar with node so I abandoned the PR.

**Comment by NoelDeMartin** [comment]
Thanks for opening the issue and the PR :). I have released a new version `0.3.0` and that should work for newer projects.

I actually didn't have to change anything in the code, rather I moved `cypress` to peerDependencies. You were probably getting all those warnings because this package dependend on Cypress v3. But instead of updating the Cypress dependency, the proper solution is to move it to peerDependencies. That way, it'll be future-proof and projects can choose which version of Cypress to use.

I also updated [the sandbox project](https://github.com/NoelDeMartin/laravel-cypress-sandbox) to Laravel 11 to make sure that everything is working properly.
